cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from.views import home,about,contact

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name="home"),
    url(r'^about/',about,name="about"),
    url(r'^contact/',contact,name="contact"),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sellers/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from products.views import (
		ProductCreateView,
		ProductUpdateView,
		SellerProductListView
	)
from .views import (
        SellerDashboard,
        SellerProductDetailRedirectView,
        SellerTransactionListView,

        )
app_name = 'sellers'
urlpatterns = [
    url(r'^$', SellerDashboard.as_view(), name='dashboard'),
    url(r'^transactions/$', SellerTransactionListView.as_view(), name='transactions'),
    url(r'^products/$', SellerProductListView.as_view(), name='product_list'), #sellers:product_list
    url(r'^products/(?P<pk>\d+)/edit/$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^products/add/$', ProductCreateView.as_view(), name='product_create'),
    ]

sellers/models.py
from django.conf import settings
from django.db import models

# Create your models here.


class SellerAccount(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	managers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="manager_sellers", blank=True)
	active = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)


	def __str__(self):
		return str(self.user.username)

shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from accounts.models import Profile
from products.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

sellers/forms.py
from django import forms


class NewSellerForm(forms.Form):
    storename = forms.CharField(max_length=100, label='store name')
    location = forms.CharField(max_length=100,label='location')
    agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

sellers/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormMixin
from .forms import NewSellerForm
from .mixins import SellerAccountMixin
from .models import SellerAccount
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from shopping_cart.models import Transaction
from products.models import Product
# Create your views here.


class SellerProductDetailRedirectView(RedirectView):
    permanent = True
    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()



class SellerTransactionListView(SellerAccountMixin,ListView):
	model = Transaction
	template_name = "sellers/transaction_list_view.html"
	def get_queryset(self):
		# account = SellerAccount.objects.filter(user=self.request.user)
		# if account.exists():
		# 	products = Product.objects.filter(seller__in=account)
		# 	return Transaction.objects.filter(product__seller__user=self.request.user)
		# return []
	    return self.get_transactions()


class SellerDashboard(SellerAccountMixin,FormMixin, View):
	form_class = NewSellerForm
	success_url = "/seller/"

	def post(self, request, *args, **kwargs):
		form = self.get_form()
		if form.is_valid():
			return self.form_valid(form)
		else:
			return self.form_invalid(form)

	def get(self, request, *args, **kwargs):
		apply_form = self.get_form() #NewSellerForm()
		# account = SellerAccount.objects.filter(user=self.request.user)
		# exists = account.exists()
		account = self.get_account()
		exists = account
		active = None
		context = {}
		if exists:
			#account = account.first()
			active = account.active
		if not exists and not active:
			context["title"] = "Apply for Account"
			context["apply_form"] = apply_form
		elif exists and not active:
			context["title"] = "Account Pending"
		elif exists and active:
			context["title"] = "Seller Dashboard"

			#products = Product.objects.filter(seller=account)
			context["products"] = self.get_products().exclude()[:4]
			transactions_today = self.get_transactions_today()
			context["transactions_today"] = transactions_today
			context["today_sales"] = self.get_today_sales()
			context["total_sales"] = self.get_total_sales()
			context["transactions"] = self.get_transactions().exclude(pk__in=transactions_today)[:5]
		else:
			pass

		return render(request, "sellers/dashboard.html", context)

	def form_valid(self, form):
		valid_data = super(SellerDashboard, self).form_valid(form)
		obj = SellerAccount.objects.create(user=self.request.user)
		return valid_data

sellers/templates/sellers/dashboard.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }}</h1>

{% if apply_form %}

<form method='POST' action=''> {% csrf_token %}
	<h3>Rules of the Marketplace</h3>
	<ol>
		<li>
			Be kind
		</li>
		<li>
			Sell well
		</li>
		<li>
			Don't steal
		</li>
	</ol>
{{ apply_form.as_p }}
<br/>
<input type='submit'/>
</form>

{% endif %}

{% if products %}
<table class="table table-hover table-bordered text-center">
	<h4>My Products<br/><small><a href='{% url "sellers:product_create" %}'>Add</a> | <a href='{% url "sellers:product_list" %}'>View All</a></small></h4>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
				<tr>
				{% for product in products %}
          <td>{{ product.name }}</td>
          <td>{{ product.description }}</td>
          <td>${{ product.price }}</td>
         </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no products.</td>
        </tr>
{% endfor %}
{% endif %}
</table>
{% if transactions %}
<div class='pull-left col-primary '>
	<h3>Today's sales are ${{ today_sales.normalize }}</h3>
{% include "sellers/transaction_list.html" with transaction_list=transactions_today %}

<br/>
	<h3>Recent Transaction History (Total Sales: ${{ total_sales.normalize }})</h3>
{% include "sellers/transaction_list.html" with transaction_list=transactions %}
<p>
<a href='{% url "sellers:transactions" %}'>View all transactions</a>
</p>
</div>
{% endif %}
{% endblock content %}

sellers/templates/sellers/product_list_view.html
{% extends "base.html" %}

{% block style %}

{% endblock style %}


{% block content %}
<h1>All Products</h1>
<table>
	{% for instance in product_list %}
    <tr class="">
    	<td>
    		{{ instance.id }}
    	</td>
    	<td>
    		<a href='{{ instance.get_absolute_url }}'>{{ instance.name }}</a>
    	</td>
    	<!-- <td>
    	{% if instance.get_featured_image %}
    	<a href='{{ instance.get_absolute_url }}'>
    		<img src='' style='max-width:100px'/></a><br/>
    	{% endif %}
    	</td> -->
    	<td>{{ instance.price }}
    	</td>
    	<td><a href='{{ instance.get_edit_url }}'>Edit</a>
    	</td>
</table>

{% endfor %}
{% endblock %}

sellers/templates/sellers/transaction_list.html
<table>
<thead>
<th>Product</th>
<th>User</th>
<th>order_id</th>
<th>Sale Total</th>
	<th></th>
</thead>
<tbody>
{% for trans in transaction_list %}
<tr>
	<td>{{ trans.product }}</td>
	<td>{{ trans.profile }}</td>
  <td>{{ trans.order_id }}</td>
	<td>{{ trans.amount }}</td>
	<td>{{ trans.timestamp|timesince }} ago</td>
</tr>
{% endfor %}
</tbody>
</table>

sellers/templates/sellers/transaction_list_view.html
{% extends "base.html" %}

{% block content %}
<h1>Transactions</h1>
<ul>

	{% include "sellers/transaction_list.html" with transaction_list=object_list %}

</ul>
{% endblock %}