accounts/urls.py
from django.conf.urls import url

from .views import my_profile,ProductDownloadView

app_name = 'accounts'

urlpatterns = [
	url(r'^profile/$', my_profile, name='my_profile'),
	url(r'^(?P<slug>[\w-]+)/download/$', ProductDownloadView.as_view(), name='download_slug'),
]

cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from.views import home,about,contact

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name="home"),
    url(r'^about/',about,name="about"),
    url(r'^contact/',contact,name="contact"),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
    product_list,
    single,
    category_single,
    search,
    ProductRatingAjaxView,
    )

app_name = 'products'

urlpatterns = [
    url(r'^$', product_list, name='product-list'),
    url(r'^ajax/rating/$', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    url(r'^category/(?P<slug>.*)/$',category_single,name="category"),
    url(r'^search/', search, name="search"),
    url(r'^(?P<slug>.*)/$',single, name="single_product"),
]


# urlpatterns = patterns('products.views',
#         url(r'^$','list_all',name="all_products"),
#         url(r'^search/','search',name="search"),
#         url(r'^add/','add_product',name="add_product"), #migth be a problem here loook very
#         url(r'^category/(?P<slug>.*)/$','category_single',name="category"),
#         url(r'^(?P<slug>.*)/images/','manage_product_image',name="manage_product_image"),
#         url(r'^(?P<slug>.*)/edit/','edit_product',name="edit_product"),
#         url(r'^(?P<slug>.*)/download/(?P<filename>.*)$','download_product',name="download_product"),
#         url(r'^(?P<slug>.*)/$','single',name="single_product"),

shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from accounts.models import Profile
from products.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

shopping_cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Profile
from products.models import Product
from shopping_cart.extras import generate_order_id, transact, generate_client_token
from shopping_cart.models import OrderItem, Order, Transaction

import datetime
import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request,**kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id
    product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    if product in request.user.profile.ebooks.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('products:product-list'))
    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()
# No module named 'slug'
    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to cart")
    return redirect(product)


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/shoping-cart.html', context)


@login_required()
def checkout(request, **kwargs):
    client_token = generate_client_token()
    existing_order = get_user_pending_order(request)
    publishKey = settings.STRIPE_PUBLISHABLE_KEY
    if request.method == 'POST':
        token = request.POST.get('stripeToken', False)
        if token:
            try:
                charge = stripe.Charge.create(
                    amount=100*existing_order.get_cart_total(),
                    currency='usd',
                    description='Example charge',
                    source=token,
                )

                return redirect(reverse('shopping_cart:update_records',
                        kwargs={
                            'token': token
                        })
                    )
            except stripe.CardError as e:
                message.info(request, "Your card has been declined.")
        else:
            result = transact({
                'amount': existing_order.get_cart_total(),
                'payment_method_nonce': request.POST['payment_method_nonce'],
                'options': {
                    "submit_for_settlement": True
                }
            })

            if result.is_success or result.transaction:
                return redirect(reverse('shopping_cart:update_records',
                        kwargs={
                            'token': result.transaction.id
                        })
                    )
            else:
                for x in result.errors.deep_errors:
                    messages.info(request, x)
                return redirect(reverse('shopping_cart:checkout'))

    context = {
        'order': existing_order,
        'client_token': client_token,
        'STRIPE_PUBLISHABLE_KEY': publishKey
    }

    return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()

    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()
    for i in order_products:
        transaction = Transaction(profile=request.user.profile,
                                    product=i,
                                    token=token,
                                    order_id=order_to_purchase.id,
                                    amount=order_to_purchase.get_cart_total(),
                                    success=True)
         # save the transcation (otherwise doesn't exist)
        transaction.save()


    # # create a transaction
    # transaction = Transaction(profile=request.user.profile,
    #                         token=token,
    #                         order_id=order_to_purchase.id,
    #                         product = order_products,
    #                         amount=order_to_purchase.get_cart_total(),
    #                         success=True)
    # # save the transcation (otherwise doesn't exist)
    # transaction.save()


    # send an email to the customer
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('shopping_cart:purchase_success'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/order-complete.html', {})

shopping_cart/templates/shopping_cart/order-complete.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
	<title>Thank you For your Purchase</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Rokkitt:100,300,400,700" rel="stylesheet">

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Ion Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

	<!-- Flexslider  -->
	<link rel="stylesheet" href="{% static 'css/flexslider.css' %}">

	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

	<!-- Date Picker -->
	<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
	<!-- Flaticons  -->
	<link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

	</head>
	<body>
	<div class="colorlib-loader"></div>
	<div id="page">
		<div class="colorlib-product">
			<div class="container">
				<div class="row row-pb-lg">
					<div class="col-sm-10 offset-md-1">
						<div class="process-wrap">
							<div class="process text-center active">
								<p><span>01</span></p>
								<h3>Shopping Cart</h3>
							</div>
							<div class="process text-center active">
								<p><span>02</span></p>
								<h3>Checkout</h3>
							</div>
							<div class="process text-center active">
								<p><span>03</span></p>
								<h3>Order Complete</h3>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-10 offset-sm-1 text-center">
						<p class="icon-addcart"><span><i class="icon-check"></i></span></p>
						<h2 class="mb-4">Thank you for purchasing, Your order is complete</h2>
						<p>
							<a href="{% url 'home' %}"class="btn btn-primary btn-outline-primary">Home</a>
							<a href="{% url 'products:product-list' %}"class="btn btn-primary btn-outline-primary"><i class="icon-shopping-cart"></i> Continue Shopping</a>
							<a href="{% url 'accounts:my_profile' %}"class="btn btn-primary btn-outline-primary">View Order</a>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>


<!-- jQuery -->
<script src="{% static 'js/jquery.min.js' %}"></script>
 <!-- popper -->
 <script src="{% static 'js/popper.min.js' %}"></script>
 <!-- bootstrap 4.1 -->
 <script src="{% static 'js/bootstrap.min.js' %}"></script>
 <!-- jQuery easing -->
 <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<!-- Waypoints -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- Flexslider -->
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script>
<!-- Owl carousel -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!-- Magnific Popup -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/magnific-popup-options.js' %}"></script>
<!-- Date Picker -->
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<!-- Stellar Parallax -->
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<!-- Main -->
<script src="{% static 'js/main1.js' %}"></script>

</body>
</html>

shopping_cart/templates/shopping_cart/order_summary.html
{% extends "base.html" %}

{% block content %}

 <section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span class="pull-right">
              <a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.product.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>
        
        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

shopping_cart/templates/shopping_cart/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1>Thank you for your purchase!</h1>
    <a href="{% url 'products:product-list' %}">Head back home</a>
{% endblock content %}

shopping_cart/templates/shopping_cart/stripe_default_form.html
<script src="https://js.stripe.com/v3/"></script>

<form action="." method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="{{ STRIPE_PUBLISHABLE_KEY }}"
    data-amount="999"
    data-name="Justdjango"
    data-description="Example charge"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto">
  </script>
</form>