cart/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from.views import home,about,contact

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',home,name="home"),
    url(r'^about/',about,name="about"),
    url(r'^contact/',contact,name="contact"),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^accounts/', include('allauth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from .views import (
    product_list,
    single,
    category_single,
    search,
    ProductRatingAjaxView,
    )

app_name = 'products'

urlpatterns = [
    url(r'^$', product_list, name='product-list'),
    url(r'^ajax/rating/$', ProductRatingAjaxView.as_view(), name='ajax_rating'),
    url(r'^category/(?P<slug>.*)/$',category_single,name="category"),
    url(r'^search/', search, name="search"),
    url(r'^(?P<slug>.*)/$',single, name="single_product"),
]


# urlpatterns = patterns('products.views',
#         url(r'^$','list_all',name="all_products"),
#         url(r'^search/','search',name="search"),
#         url(r'^add/','add_product',name="add_product"), #migth be a problem here loook very
#         url(r'^category/(?P<slug>.*)/$','category_single',name="category"),
#         url(r'^(?P<slug>.*)/images/','manage_product_image',name="manage_product_image"),
#         url(r'^(?P<slug>.*)/edit/','edit_product',name="edit_product"),
#         url(r'^(?P<slug>.*)/download/(?P<filename>.*)$','download_product',name="download_product"),
#         url(r'^(?P<slug>.*)/$','single',name="single_product"),

shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from accounts.models import Profile
from products.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

products/forms.py
from django import forms

from django.utils.text import slugify

from .models import Product,ProductImage

PUBLISH_CHOICES = (
	#('', ""),
	('publish', "Publish"),
	('draft', "Draft"),
)

class ProductAddForm(forms.Form):
	name = forms.CharField(label='Your Title', widget= forms.TextInput(
		attrs={
			"class": "custom-class",
			"placeholder": "Name",
		}))
	description = forms.CharField(widget=forms.Textarea(
			attrs={
				"class": "my-custom-class",
				"placeholder": "Description",
				"some-attr": "this",
			}
	)) #this might be a problem looook very !
	price  = forms.DecimalField()
	publish = forms.ChoiceField(widget=forms.RadioSelect, choices=PUBLISH_CHOICES, required=False)


	def clean_price(self):
		price = self.cleaned_data.get("price")
		if price <= 1.00:
			raise forms.ValidationError("Price must be greater than $1.00")
		elif price >= 99.99:
			raise forms.ValidationError("Price must be less than $100.00")
		else:
			return price

	def clean_title(self):
		name = self.cleaned_data.get("name")
		if len(name) > 3:
			return name
		else:
			raise forms.ValidationError("Name must be greater than 3 characters long.")



class ProductModelForm(forms.ModelForm):
	tags = forms.CharField(label='Related tags', required=False)
	publish = forms.ChoiceField(widget=forms.RadioSelect, choices=PUBLISH_CHOICES, required=False)
	# description = forms.CharField(widget=forms.Textarea(
	# 		attrs={
	# 			"class": "my-custom-class",
	# 			"placeholder": "Description",
	# 			"some-attr": "this",
	# 		}
	# ))
	class Meta:
		model = Product
		fields = [
			"name",
			"description",
			"price",
			"download",
            "slug",
		]
		widgets = {
			"description": forms.Textarea(
					attrs={
						"placeholder": "New Description"
					}
				),
			"name": forms.TextInput(
				attrs= {
					"placeholder": "Name"
				}
			)
		}

	def clean(self, *args, **kwargs):
		cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
		#title = cleaned_data.get("title")
		#slug = slugify(title)
		#qs = Product.objects.filter(slug=slug).exists()
		#if qs:
		# 	raise forms.ValidationError("Title is taken, new title is needed. Please try again.")
		return cleaned_data

	def clean_price(self):
		price = self.cleaned_data.get("price")
		if price <= 1.00:
			raise forms.ValidationError("Price must be greater than $1.00")
		elif price >= 100.00:
			raise forms.ValidationError("Price must be less than $100.00")
		else:
			return price

	def clean_title(self):
		name = self.cleaned_data.get("name")
		if len(name) > 3:
			return name
		else:
			raise forms.ValidationError("Name must be greater than 3 characters long.")

products/views.py
from __future__ import unicode_literals
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.db.models import Q,Avg,Count
from django.shortcuts import render
from django.http import Http404, HttpResponse, JsonResponse
from shopping_cart.models import Order
from accounts.models import Profile

from .models import Product,Category,ProductImage,ProductRating
from .mixins import ProductManagerMixin
from cart.mixins import (
			LoginRequiredMixin,
			MultiSlugMixin,
			SubmitBtnMixin,
			AjaxRequiredMixin
			)
from sellers.mixins import SellerAccountMixin
from .forms import ProductAddForm, ProductModelForm
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

class ProductRatingAjaxView(AjaxRequiredMixin, View):
	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return JsonResponse({}, status=401)

		user = request.user
		product_id = request.POST.get("product_id")
		rating_value = request.POST.get("rating_value")
		exists = Product.objects.filter(id=product_id).exists()
		if not exists:
			return JsonResponse({}, status=404)

		try:
			product_obj = Product.object.get(id=product_id)
		except:
			product_obj = Product.objects.filter(id=product_id).first()

		rating_obj, rating_obj_created = ProductRating.objects.get_or_create(
				user=user,
				product=product_obj
				)
		try:
			rating_obj = ProductRating.objects.get(user=user, product=product_obj)
		except ProductRating.MultipleObjectsReturned:
			rating_obj = ProductRating.objects.filter(user=user, product=product_obj).first()
		except:
			#rating_obj = ProductRating.objects.create(user=user, product=product_obj)
			rating_obj = ProductRating()
			rating_obj.user = user
			rating_obj.product = product_obj
		rating_obj.rating = int(rating_value)
		myproducts = user.profile.ebooks.all()

		if product_obj in myproducts:
			rating_obj.verified = True
		# verify ownership
		rating_obj.save()

		data = {
			"success": True
		}
		return JsonResponse(data)

class ProductCreateView(SellerAccountMixin, SubmitBtnMixin, CreateView):
	model = Product
	template_name = "form.html"
	form_class = ProductModelForm
	#success_url = "/products/"
	submit_btn = "Add Product"

	def form_valid(self, form):
		seller = self.get_account()
		form.instance.seller = seller
		valid_data = super(ProductCreateView, self).form_valid(form)
		#tags = form.cleaned_data.get("tags")
		# if tags:
		# 	tags_list = tags.split(",")
		# 	for tag in tags_list:
		# 		if not tag == " ":
		# 			new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
		# 			new_tag.products.add(form.instance)
		return valid_data

class ProductUpdateView(ProductManagerMixin,SubmitBtnMixin, MultiSlugMixin, UpdateView):
	model = Product
	template_name = "form.html"
	form_class = ProductModelForm
	#success_url = "/products/"
	submit_btn = "Update Product"
	def get_initial(self):
		initial = super(ProductUpdateView,self).get_initial()
		print (initial)
		# tags = self.get_object().tag_set.all()
		# initial["tags"] = ", ".join([x.title for x in tags])
		"""
		tag_list = []
		for x in tags:
			tag_list.append(x.title)
		"""
		return initial
	def form_valid(self, form):
		valid_data = super(ProductUpdateView, self).form_valid(form)
		# tags = form.cleaned_data.get("tags")
		# obj = self.get_object()
		# obj.tag_set.clear()
		# if tags:
		# 	tags_list = tags.split(",")
        #
		# 	for tag in tags_list:
		# 		if not tag == " ":
		# 			new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
		# 			new_tag.products.add(self.get_object())
		return valid_data

class SellerProductListView(SellerAccountMixin, ListView):
	model = Product
	template_name = "sellers/product_list_view.html"

	def get_queryset(self, *args, **kwargs):
		qs = super(SellerProductListView, self).get_queryset(**kwargs)
		qs = qs.filter(seller=self.get_account())
		query = self.request.GET.get("q")
		if query:
			qs = qs.filter(
					Q(name__icontains=query)|
					Q(description__icontains=query)
				).order_by("name")
		return qs

@login_required
def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
    	user_order = filtered_orders[0]
    	user_order_items = user_order.items.all()
    	current_order_products = [product.product for product in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, "products/product.html", context)


@login_required()
def single(request,slug):
    product = Product.objects.get(slug=slug)
    object_list = Product.objects.all()
    my_rating = []
    images = product.productimage_set.all()
    categories = product.category_set.all()
    rating_avg = product.productrating_set.aggregate(Avg("rating"), Count("rating"))
    if request.user.is_authenticated:
	    rating_obj = ProductRating.objects.filter(user=request.user, product=product)
	    if rating_obj.exists():
		    my_rating =  rating_obj.first().rating

    related = []
    if len(categories) >=1:
        for category in categories:
            products_category = category.product.all()
            for item in products_category:
                if not item == product:
                    related.append(item)
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
	    user_order = filtered_orders[0]
	    user_order_items = user_order.items.all()
	    current_order_products = [product.product for product in user_order_items]

    context = {
        "product":product,
        "categories":categories,
        "edit":True,
        "images":images,
        "related":related,
		"rating_avg":rating_avg,
		"my_rating":my_rating,
		"object_list":object_list,
		"current_order_products":current_order_products
    }
    return render(request,"products/product-detail.html",context)
#
# def search(request):
#     q = request.GET.get('q', '')
#
#     product_queryset = Product.objects.filter(
#         Q(name__icontains=q)|
#         Q(description__icontains=q)
#     )
#     category_queryset = Category.objects.filter(
#         Q(title__icontains=q)|
#         Q(description__icontains=q)
#     )
#     results = list(chain(product_queryset,category_queryset))
#     context = {
#         'query': q,
#         'product_queryset':product_queryset,
#         'category_queryset':category_queryset,
#         'results':results,
#     }
#
#     return render(request,"products/search.html", context)
def search(request):
    try:
        q = request.GET.get('q', '')
    except:
        q = False
    if q:
        query = q
    else :
        query = None


    product_queryset = Product.objects.filter(
        Q(name__icontains=q)|
        Q(description__icontains=q)
    )
    category_queryset = Category.objects.filter(
        Q(title__icontains=q)|
        Q(description__icontains=q)
    )
    results = list(chain(product_queryset,category_queryset))
    context = {
        'query':query,
        'product_queryset':product_queryset,
        'category_queryset':category_queryset,
        'results':results,
    }

    return render(request,"products/search.html", context)

def category_single(request,slug):
    try:
        category = Category.objects.get(slug=slug)
    except:
        raise Http404
    products = category.product.all()
    related = []
    for item in products:
        product_categories = item.category_set.all()
        for single_category in product_categories:
            if not single_category == category:
                related.append(single_category)
    context = {
        'category':category,
        'products':products,
        'related':related,
    }
    return render(request,"products/category.html",context)

products/templates/products/product-detail.html
{% extends "layout.html" %}
{% load static %}
{% block style %}
<style>

.rating {
    float:left;
     width: 200px;
}
/* :not(:checked) is a filter, so that browsers that don’t support :checked don’t
   follow these rules. Every browser that supports :checked also supports :not(), so
   it doesn’t make the test unnecessarily selective */
.rating:not(:checked) > input {
    position:absolute;
    top:-9999px;
    clip:rect(0,0,0,0);
}
.rating:not(:checked) > label {
    float:right;
    width:1em;
    padding:0 .1em;
    overflow:hidden;
    white-space:nowrap;
    cursor:pointer;
    font-size:200%;
    line-height:1.2;
    color:#ddd;
    text-shadow:1px 1px #bbb, 2px 2px #666, .1em .1em .2em rgba(0,0,0,.5);
}
.rating:not(:checked) > label:before {
    content: '★ ';
}
.rating > input:checked ~ label {
    color: #f70;
    text-shadow:1px 1px #c60, 2px 2px #940, .1em .1em .2em rgba(0,0,0,.5);
}
.rating:not(:checked) > label:hover,
.rating:not(:checked) > label:hover ~ label {
    color: gold;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}
.rating > input:checked + label:hover,
.rating > input:checked + label:hover ~ label,
.rating > input:checked ~ label:hover,
.rating > input:checked ~ label:hover ~ label,
.rating > label:hover ~ input:checked ~ label {
    color: #ea0;
    text-shadow:1px 1px goldenrod, 2px 2px #B57340, .1em .1em .2em rgba(0,0,0,.5);
}
.rating > label:active {
    position:relative;
    top:2px;
    left:2px;
}

</style>
{% endblock style %}

<script>
$(document).ready(function(){
{% block jquery %}
$(".rating input[value='{{ my_rating }}']").attr("checked", "checked");
$(".rating input[type='radio']").click(function(event){
	// event.preventDefault()
	var inputValue = $(this).val()
	console.log(inputValue)
	var request = $.ajax({
		method: "POST",
		url: "{% url 'products:ajax_rating' %}",
		data: {
			product_id: "{{ product.id }}",
			rating_value: inputValue,

		}
	})
	request.done(function(data){
	})
	request.fail(function(jqXHR, textStatus){
		if (jqXHR.status == 404) {
			alert("Page not found!")
		} else if (jqXHR.status == 401) {
			alert("You must be logged in to do this.")
		} else {
			alert("There was an error with your request. Please try again.")
		}
	})
})

{% endblock jquery %}
})
</script>

	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="index.html" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<a href="product.html" class="stext-109 cl8 hov-cl1 trans-04">
				Men
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Lightweight Jacket
			</span>
		</div>
	</div>

{% block content %}
	<!-- Product Detail -->
<br/>
	<section class="sec-product-detail bg0 p-t-65 p-b-60">
		<div class="container">
			<div class="row">

				<div class="col-md-6 col-lg-7 p-b-30">
					<div class="p-l-25 p-r-30 p-lr-0-lg">
						<div class="wrap-slick3 flex-sb flex-w">
							<div class="wrap-slick3-dots"></div>
							<div class="wrap-slick3-arrows flex-sb-m flex-w"></div>

							<div class="slick3 gallery-lb">
								{% for img in images %}
								<div class="item-slick3" data-thumb="{{ MEDIA_URL }}{{ img.image.url }}">
									<div class="wrap-pic-w pos-relative">
										<img src="{{ MEDIA_URL }}{{ img.image.url }}" alt="IMG-PRODUCT">

										<a class="flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04" href="{{ MEDIA_URL }}{{ img.image.url }}">
											<i class="fa fa-expand"></i>
										</a>
									</div>
								</div>
								{% endfor %}
							</div>

						</div>
					</div>
				</div>

				<div class="col-md-6 col-lg-5 p-b-30">
					<div class="p-r-50 p-t-5 p-lr-0-lg">
						<h4 class="mtext-105 cl2 js-name-detail p-b-14">
							{{ product }}
						</h4>

						<span class="mtext-106 cl2">
						${{ product.get_price }}
						</span>

						<p class="stext-102 cl3 p-t-23">
							{{ product.description }}
						</p>
						<p>Purchases: {{ product.transaction_set.count }}</p>
						<p>
										<strong>Ratings</strong>

									<div class="rating">
										<input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="super cool">5 stars</label>
										<input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
										<input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="normal">3 stars</label>
										<input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
										<input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks">1 star</label>
									</div>
										<br/>
										<br/>
										<p>
										{{ rating_avg.rating__avg }} Average <br/>
										Rating by {{ rating_avg.rating__count }} Users.
										</p>
						<br/>
							<div class="flex-w flex-r-m p-b-10">
								<div class="size-204 flex-w flex-m respon6-next">
                  {% if product in user.profile.ebooks.all %}
                    You own this
                  {% elif product in current_order_products %}
                  <a href="{% url 'shopping_cart:order_summary' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">Go to cart</a>
                  {% else %}
                  <button class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 js-addcart-detail">
										<a href="{% url 'shopping_cart:add_to_cart' product.id %}">Add to cart</a>
                  </button>
                  {% endif %}
								</div>

							</div>

						</div>

						<!--  -->
						<div class="flex-w flex-m p-l-100 p-t-40 respon7">

							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Facebook">
								<i class="fa fa-facebook"></i>
							</a>

							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Twitter">
								<i class="fa fa-twitter"></i>
							</a>

							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Google Plus">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
						<br/>
						{% if categories %}
						<div class="panel panel-default">
						<div class="panel-heading">
						<h4 class="panel-title">Categor{% if categories|length == 1 %}y{% else %}ies{% endif %}</h4>
						  </div>
						<div class="panel-body">
						<ul>

						{% for item in categories %}
						<li>
						  <a href="{{ item.get_absolute_url }}">{{ item }}</a>
						</li>
						{% endfor %}
						</ul>
						{% endif %}
					</div>
			  	</div>


					</div>

				</div>

			</div>

		</div>

	</section>

	<!-- Related Products -->
	<section class="sec-relate-product bg0 p-t-45 p-b-105">
		<div class="container">
			<div class="p-b-45">
				<h3 class="ltext-106 cl5 txt-center">
					Related Products
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">

        {% for item in related %}
					<div class="item-slick2 p-l-15 p-r-15 p-t-15 p-b-15">
						<!-- Block2 -->
						<div class="block2">
							<div class="block2-pic hov-img0">
								<img src="{{ MEDIA_URL }}{{ item.get_featured_image.url }}" alt="IMG-PRODUCT">

								<a href="{{ item.get_absolute_url }}" class="block2-btn flex-c-m stext-103 cl2 size-102 bg0 bor2 hov-btn1 p-lr-15 trans-04">
									View
								</a>
							</div>

							<div class="block2-txt flex-w flex-t p-t-14">
								<div class="block2-txt-child1 flex-col-l ">
									<a href="{{ item.get_absolute_url }}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
										{{ item }}
									</a>

									<span class="stext-105 cl3">
										${{ item.price }}
									</span>
								</div>

								<div class="block2-txt-child2 flex-r p-t-3">
									<a href="#" class="btn-addwish-b2 dis-block pos-relative js-addwish-b2">
										<!-- <img class="icon-heart1 dis-block trans-04" src="{% static 'images/icons/icon-heart-01.png' %}" alt="ICON"> -->
										<img class="icon-heart2 dis-block trans-04 ab-t-l" src="{% static 'images/icons/icon-heart-02.png' %}" alt="ICON">
									</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</section>


	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>

	<!-- Modal1 -->
	{% endblock content %}
{% block script %}
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
	<script>
		$(".js-select2").each(function(){
			$(this).select2({
				minimumResultsForSearch: 20,
				dropdownParent: $(this).next('.dropDownSelect2')
			});
		})
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/slick/slick.min.js' %}"></script>
	<script src="{% static 'js/slick-custom.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/parallax100/parallax100.js' %}"></script>
	<script>
        $('.parallax100').parallax100();
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
	<script>
		$('.gallery-lb').each(function() { // the containers for all your galleries
			$(this).magnificPopup({
		        delegate: 'a', // the selector for gallery item
		        type: 'image',
		        gallery: {
		        	enabled:true
		        },
		        mainClass: 'mfp-fade'
		    });
		});
	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/isotope/isotope.pkgd.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/sweetalert/sweetalert.min.js' %}"></script>
	<script>
		$('.js-addwish-b2, .js-addwish-detail').on('click', function(e){
			e.preventDefault();
		});

		$('.js-addwish-b2').each(function(){
			var nameProduct = $(this).parent().parent().find('.js-name-b2').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");

				$(this).addClass('js-addedwish-b2');
				$(this).off('click');
			});
		});

		$('.js-addwish-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.js-name-detail').html();

			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");

				$(this).addClass('js-addedwish-detail');
				$(this).off('click');
			});
		});

		/*---------------------------------------------*/

		$('.js-addcart-detail').each(function(){
			var nameProduct = $(this).parent().parent().parent().parent().find('.js-name-detail').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to cart !", "success");
			});
		});

	</script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
	<script>
		$('.js-pscroll').each(function(){
			$(this).css('position','relative');
			$(this).css('overflow','hidden');
			var ps = new PerfectScrollbar(this, {
				wheelSpeed: 1,
				scrollingThreshold: 1000,
				wheelPropagation: false,
			});

			$(window).on('resize', function(){
				ps.update();
			})
		});
	</script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>
{% endblock script %}
</body>
</html>